plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
def targetJavaVersion = (project.findProperty("java_version") ?: "21") as int

base {
    archivesName = project.archives_base_name
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.toVersion(targetJavaVersion)
    targetCompatibility = JavaVersion.toVersion(targetJavaVersion)
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    modCompileOnly "maven.modrinth:modmenu:${modmenu_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = targetJavaVersion
}

processResources {
    def props = [
            version                : project.version,
            minecraft_version      : project.minecraft_version,
            minecraft_version_range: project.minecraft_version_range,
            loader_version         : project.loader_version,
            fabric_api_version     : project.fabric_api_version,
            java_version           : project.java_version,
            modmenu_version        : project.modmenu_version
    ]

    inputs.properties(props)

    filesMatching('fabric.mod.json') {
        expand(props)
    }
}
